easy_admin:
    entities:

      Page:
        class: App\ReaccionEstudio\ReaccionCMSBundle\Entity\Page
        list: 
          fields: ['id', 'name', 'isEnabled', 'updatedAt' ]
        form: 
          fields: 
            - { type: 'group' , label: 'Page information', icon: 'file-text' }
            - name
            - { property: 'isEnabled', type: 'checkbox' }

            - { type: 'group' , label: 'Seo information', icon: 'search' }
            - slug
            - seoTitle
            - seoDescription
