home:
    path: /
    controller: App\Controller\HomeController::index

contact:
    path: /contacto
    controller: App\Controller\ContactController::index

cookies:
    path: /politica-de-cookies
    controller: App\Controller\TermsPagesController::cookies

services:
    path: /servicios
    controller: App\Controller\ServicesController::index

sendContactEmail:
    path: /send-contact-email
    controller: App\Controller\SendContactEmailController::index
    methods: POST
    options:
      expose: true

wePhoneYouEmail:
    path: /we-phone-you-email
    controller: App\Controller\SendWePhoneYouEmailController::index
    methods: POST
    options:
      expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"